truncate table public.questions;

insert into public.questions (category, question, options, correct_answer_index) values
('football', 'Which country won the first FIFA World Cup in 1930?', ARRAY['Brazil','Uruguay','Argentina','Italy'], 1),
('football', 'How many players are on a football team on the pitch at one time (excluding substitutes)?', ARRAY['9','10','11','12'], 2),
('football', 'Which club has won the most UEFA Champions League titles?', ARRAY['AC Milan','Bayern Munich','Real Madrid','Liverpool'], 2),
('football', 'Who is the all-time top scorer for the Brazilian national team?', ARRAY['Pele','Ronaldo','Neymar','Romario'], 2),
('football', 'Which country hosted the 2014 FIFA World Cup?', ARRAY['Germany','Brazil','South Africa','Russia'], 1),
('football', 'What is the maximum number of substitutions allowed in a standard modern football match?', ARRAY['3','4','5','6'], 2),
('football', 'Which player has won the most Ballon d''Or awards?', ARRAY['Cristiano Ronaldo','Lionel Messi','Michel Platini','Johan Cruyff'], 1),
('football', 'Which English club is nicknamed "The Red Devils"?', ARRAY['Liverpool','Arsenal','Manchester United','Chelsea'], 2),
('football', 'How long is a standard football match (excluding stoppage time)?', ARRAY['80 minutes','90 minutes','100 minutes','120 minutes'], 1),
('football', 'Which country won the 2018 FIFA World Cup?', ARRAY['Croatia','Belgium','France','Germany'], 2),
('football', 'What shape is a red card used to signal in football?', ARRAY['Rectangle','Square','Circle','Triangle'], 0),
('football', 'Which Argentine player is nicknamed "La Pulga" (The Flea)?', ARRAY['Sergio Aguero','Lionel Messi','Diego Maradona','Angel Di Maria'], 1),
('football', 'Which league is Manchester City part of?', ARRAY['La Liga','Serie A','Premier League','Bundesliga'], 2),
('football', 'What is the offside rule primarily designed to prevent?', ARRAY['Time wasting','Goal hanging','Rough tackles','Handballs'], 1),
('football', 'Which country has won the most FIFA World Cups?', ARRAY['Germany','Argentina','Italy','Brazil'], 3),
('football', 'Which stadium is known as "The Theatre of Dreams"?', ARRAY['Anfield','Old Trafford','Emirates Stadium','Camp Nou'], 1),
('football', 'Who won the Ballon d''Or in 2022?', ARRAY['Lionel Messi','Kylian Mbappe','Karim Benzema','Erling Haaland'], 2),
('football', 'Which Italian club is known as "The Old Lady"?', ARRAY['AC Milan','Inter Milan','Juventus','Napoli'], 2),
('football', 'What competition is nicknamed "The Copa del Rey"?', ARRAY['Italian Cup','French Cup','Spanish Cup','English Cup'], 2),
('football', 'How many minutes make up each half of a standard football match?', ARRAY['40','45','50','60'], 1),
('football', 'Which player scored the "Hand of God" goal in the 1986 World Cup?', ARRAY['Pele','Diego Maradona','Zico','Michel Platini'], 1),
('football', 'Which country did Cristiano Ronaldo represent internationally?', ARRAY['Spain','Brazil','Portugal','Italy'], 2),
('football', 'What is awarded to a team when an opponent commits a foul inside their own penalty area?', ARRAY['Free kick','Corner kick','Penalty kick','Throw-in'], 2),
('football', 'Which club won the UEFA Champions League in 2019?', ARRAY['Barcelona','Liverpool','Tottenham','Real Madrid'], 1),
('football', 'Who is widely considered the founder of "Total Football"?', ARRAY['Johan Cruyff','Rinus Michels','Pep Guardiola','Arrigo Sacchi'], 1),
('football', 'Which country won the UEFA Euro 2020 (played in 2021)?', ARRAY['England','Spain','Italy','France'], 2),
('football', 'What is the term for scoring three goals in a single match by one player?', ARRAY['Brace','Hat-trick','Treble','Triplet'], 1),
('football', 'Which position is primarily responsible for stopping the ball from entering the goal?', ARRAY['Striker','Midfielder','Goalkeeper','Defender'], 2),
('football', 'Which South American country is nicknamed "La Albiceleste"?', ARRAY['Brazil','Chile','Argentina','Uruguay'], 2),
('football', 'What color card is shown for a caution/warning in football?', ARRAY['Red','Yellow','Blue','Orange'], 1),
('football', 'Which club does Lionel Messi play for as of the 2023 MLS season?', ARRAY['Paris Saint-Germain','Barcelona','Inter Miami','Al Hilal'], 2),
('football', 'How many World Cups has Germany won?', ARRAY['2','3','4','5'], 2),
('football', 'Which country is home to the football club Bayern Munich?', ARRAY['Austria','Germany','Switzerland','Netherlands'], 1),
('football', 'What is the standard diameter category of a football, size-wise, used in professional matches?', ARRAY['Size 3','Size 4','Size 5','Size 6'], 2),
('football', 'Football''s governing body FIFA is headquartered in which city?', ARRAY['Paris','Geneva','Zurich','London'], 2),
('football', 'Who managed Manchester United for the longest period, from 1986 to 2013?', ARRAY['Jose Mourinho','Alex Ferguson','David Moyes','Louis van Gaal'], 1),
('football', 'Which player is nicknamed "CR7"?', ARRAY['Cristiano Ronaldo','Ronaldinho','Ronaldo Nazario','Cesc Fabregas'], 0),
('football', 'What is a "clean sheet" in football?', ARRAY['Winning by 5 goals','Not conceding a goal in a match','Scoring in every match','A perfect passing record'], 1),
('football', 'Which country won the first-ever UEFA European Championship in 1960?', ARRAY['France','Spain','Soviet Union','West Germany'], 2),
('football', 'What annual match is contested by the winners of the Premier League and the FA Cup at the start of the season?', ARRAY['FA Cup Final','Community Shield','League Cup Final','Super Cup'], 1),
('football', 'Which Brazilian is widely regarded as one of the greatest players of all time, winning 3 World Cups?', ARRAY['Ronaldinho','Pele','Kaka','Rivaldo'], 1),
('football', 'What is VAR in modern football?', ARRAY['Video Assistant Referee','Virtual Athletic Rating','Verified Action Review','Video Analysis Room'], 0),
('football', 'Which club is based at Camp Nou?', ARRAY['Real Madrid','Atletico Madrid','Barcelona','Sevilla'], 2),
('football', 'Which country won the 2010 FIFA World Cup?', ARRAY['Netherlands','Spain','Germany','Uruguay'], 1),
('football', 'What is the term for a goal scored directly from a corner kick?', ARRAY['Own goal','Olympico','Volley','Header'], 1),
('football', 'Who holds the record for most goals scored in a single World Cup tournament (13 goals)?', ARRAY['Pele','Just Fontaine','Ronaldo','Miroslav Klose'], 1),
('football', 'Which English club plays home matches at "The Emirates Stadium"?', ARRAY['Chelsea','Tottenham Hotspur','Arsenal','West Ham'], 2),
('football', 'What does "extra time" refer to in a knockout football match?', ARRAY['Injury stoppage','Additional 30 minutes after a draw','Half-time break','Penalty shootout'], 1),
('football', 'Which country did Diego Maradona play for internationally?', ARRAY['Uruguay','Argentina','Chile','Colombia'], 1),
('football', 'What is the current trophy awarded to the winner of the FIFA World Cup called?', ARRAY['The Golden Cup','FIFA World Cup Trophy','The Champions Trophy','Jules Rimet Trophy'], 1),
('football', 'Which club won the inaugural Premier League title in the 1992-93 season?', ARRAY['Manchester United','Arsenal','Liverpool','Blackburn Rovers'], 0),
('football', 'Erling Haaland plays club football for which team as of 2023?', ARRAY['Borussia Dortmund','Manchester City','Real Madrid','RB Leipzig'], 1),
('football', 'What is a "nutmeg" in football slang?', ARRAY['A type of formation','Passing the ball through an opponent''s legs','A penalty technique','A defensive tactic'], 1),
('football', 'Which country won the Copa America in 2021?', ARRAY['Brazil','Argentina','Uruguay','Chile'], 1),
('football', 'How many teams competed in the group stage of the FIFA World Cup before 2026 expansion?', ARRAY['24','28','32','36'], 2),
('football', 'Which position typically wears the number 1 shirt?', ARRAY['Striker','Goalkeeper','Center-back','Winger'], 1),
('football', 'What is the name of the biennial club competition contested by European league winners, known as the Champions League?', ARRAY['UEFA Cup','UEFA Champions League','Europa League','Conference League'], 1),
('football', 'Which country''s national team is nicknamed "Les Bleus"?', ARRAY['Belgium','Italy','France','Portugal'], 2),
('football', 'Who is the current (as of 2023) all-time leading goalscorer in Premier League history?', ARRAY['Wayne Rooney','Alan Shearer','Harry Kane','Sergio Aguero'], 1),
('football', 'What is the term for when a match ends level and goes to a shootout?', ARRAY['Sudden death','Penalty shootout','Extra time','Golden goal'], 1),
('football', 'Which club has its home ground at "San Siro" alongside AC Milan?', ARRAY['Juventus','Roma','Inter Milan','Napoli'], 2),
('football', 'What is the maximum squad size typically named for a World Cup tournament?', ARRAY['20','23','26','30'], 2),
('football', 'Which country eliminated Brazil 7-1 in the 2014 World Cup semi-final?', ARRAY['Argentina','Netherlands','Germany','France'], 2),
('football', 'Zinedine Zidane represented which country as a player?', ARRAY['Algeria','Morocco','France','Tunisia'], 2),
('football', 'What is the name for a foul that results in an automatic caution for stopping a clear goal-scoring opportunity?', ARRAY['Professional foul','Handball','Time-wasting','Dissent'], 0),
('football', 'Which country hosted the first FIFA Women''s World Cup in 1991?', ARRAY['USA','China','Sweden','Germany'], 1),
('football', 'What is Kylian Mbappe''s nationality?', ARRAY['Belgian','French','Cameroonian','Senegalese'], 1),
('football', 'Which club did Pep Guardiola manage before Manchester City?', ARRAY['Real Madrid','Bayern Munich','Chelsea','Juventus'], 1),
('football', 'How many points does a win typically earn a team in most football league tables?', ARRAY['1','2','3','4'], 2),
('football', 'What is the term for a match with no goals scored by either team?', ARRAY['Draw','Clean sheet','Goalless draw','Stalemate'], 2),
('football', 'Which country did Ronaldinho represent internationally?', ARRAY['Argentina','Brazil','Portugal','Spain'], 1),
('football', 'What is the primary role of a "sweeper" in football?', ARRAY['Score goals','Take corners','Defend behind the back line','Take throw-ins'], 2),
('football', 'Which African country reached the World Cup semi-finals for the first time in 2022?', ARRAY['Nigeria','Ghana','Morocco','Senegal'], 2),
('football', 'What competition do the winners of each European domestic league qualify for?', ARRAY['Europa League','UEFA Champions League','Conference League','Super Cup'], 1),
('football', 'Which club is Harry Kane associated with as of the 2023-24 season?', ARRAY['Tottenham Hotspur','Bayern Munich','Manchester United','Chelsea'], 1),

('general_knowledge', 'What is the capital of France?', ARRAY['Berlin','Madrid','Paris','Rome'], 2),
('general_knowledge', 'How many continents are there on Earth?', ARRAY['5','6','7','8'], 2),
('general_knowledge', 'What is the largest planet in our solar system?', ARRAY['Earth','Jupiter','Saturn','Neptune'], 1),
('general_knowledge', 'Which gas do plants absorb from the atmosphere for photosynthesis?', ARRAY['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'], 2),
('general_knowledge', 'What is the chemical symbol for gold?', ARRAY['Ag','Au','Gd','Go'], 1),
('general_knowledge', 'Who wrote the play "Romeo and Juliet"?', ARRAY['Charles Dickens','William Shakespeare','Jane Austen','Mark Twain'], 1),
('general_knowledge', 'What is the largest ocean on Earth?', ARRAY['Atlantic Ocean','Indian Ocean','Arctic Ocean','Pacific Ocean'], 3),
('general_knowledge', 'How many days are there in a leap year?', ARRAY['364','365','366','367'], 2),
('general_knowledge', 'What is the smallest country in the world by area?', ARRAY['Monaco','San Marino','Vatican City','Liechtenstein'], 2),
('general_knowledge', 'Which planet is known as the "Red Planet"?', ARRAY['Venus','Mars','Jupiter','Mercury'], 1),
('general_knowledge', 'What is the currency of Japan?', ARRAY['Yuan','Won','Yen','Ringgit'], 2),
('general_knowledge', 'How many bones are there in the adult human body?', ARRAY['186','206','226','246'], 1),
('general_knowledge', 'Who painted the Mona Lisa?', ARRAY['Vincent van Gogh','Pablo Picasso','Leonardo da Vinci','Claude Monet'], 2),
('general_knowledge', 'What is the tallest mountain in the world?', ARRAY['K2','Kangchenjunga','Mount Everest','Lhotse'], 2),
('general_knowledge', 'Which element has the chemical symbol "O"?', ARRAY['Osmium','Oxygen','Gold','Silver'], 1),
('general_knowledge', 'What is the longest river in the world?', ARRAY['Amazon River','Nile River','Yangtze River','Mississippi River'], 1),
('general_knowledge', 'How many strings does a standard guitar have?', ARRAY['4','5','6','7'], 2),
('general_knowledge', 'What is the capital city of Japan?', ARRAY['Osaka','Kyoto','Tokyo','Nagoya'], 2),
('general_knowledge', 'Which organ in the human body is primarily responsible for pumping blood?', ARRAY['Lungs','Liver','Heart','Kidneys'], 2),
('general_knowledge', 'What is the freezing point of water in Celsius?', ARRAY['-10','0','10','32'], 1),
('general_knowledge', 'Which country is known as the "Land of the Rising Sun"?', ARRAY['China','South Korea','Japan','Thailand'], 2),
('general_knowledge', 'What is the largest mammal in the world?', ARRAY['African elephant','Blue whale','Giraffe','Sperm whale'], 1),
('general_knowledge', 'How many colors are there in a rainbow?', ARRAY['5','6','7','8'], 2),
('general_knowledge', 'What is the capital of Italy?', ARRAY['Milan','Venice','Naples','Rome'], 3),
('general_knowledge', 'Which planet is closest to the sun?', ARRAY['Venus','Mercury','Earth','Mars'], 1),
('general_knowledge', 'What is the main language spoken in Brazil?', ARRAY['Spanish','Portuguese','French','Italian'], 1),
('general_knowledge', 'How many players are on a standard basketball team on the court at one time?', ARRAY['4','5','6','7'], 1),
('general_knowledge', 'What is the chemical formula for water?', ARRAY['CO2','H2O','O2','NaCl'], 1),
('general_knowledge', 'Who is known as the "Father of Modern Physics"?', ARRAY['Isaac Newton','Albert Einstein','Galileo Galilei','Niels Bohr'], 1),
('general_knowledge', 'What is the largest desert in the world (by area, including polar deserts)?', ARRAY['Sahara Desert','Arabian Desert','Antarctic Desert','Gobi Desert'], 2),
('general_knowledge', 'Which country gifted the Statue of Liberty to the United States?', ARRAY['United Kingdom','Spain','France','Italy'], 2),
('general_knowledge', 'What is the study of living organisms called?', ARRAY['Chemistry','Physics','Biology','Geology'], 2),
('general_knowledge', 'How many minutes are there in a full day?', ARRAY['1200','1440','1600','1800'], 1),
('general_knowledge', 'Which is the smallest planet in our solar system?', ARRAY['Mars','Mercury','Venus','Pluto'], 1),
('general_knowledge', 'What is the national language of Egypt?', ARRAY['Arabic','Hebrew','Turkish','Persian'], 0),
('general_knowledge', 'Who developed the theory of evolution by natural selection?', ARRAY['Gregor Mendel','Charles Darwin','Louis Pasteur','Isaac Newton'], 1),
('general_knowledge', 'What is the hardest natural substance on Earth?', ARRAY['Gold','Iron','Diamond','Quartz'], 2),
('general_knowledge', 'Which country has the largest population in the world (as of the early 2020s)?', ARRAY['United States','India','China','Indonesia'], 2),
('general_knowledge', 'What do you call a group of lions?', ARRAY['Pack','Pride','Herd','Flock'], 1),
('general_knowledge', 'What is the capital of Canada?', ARRAY['Toronto','Vancouver','Ottawa','Montreal'], 2),
('general_knowledge', 'How many sides does a hexagon have?', ARRAY['5','6','7','8'], 1),
('general_knowledge', 'What is the primary gas found in the Earth''s atmosphere?', ARRAY['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'], 2),
('general_knowledge', 'Who wrote the novel "1984"?', ARRAY['Aldous Huxley','George Orwell','Ray Bradbury','H.G. Wells'], 1),
('general_knowledge', 'What is the tallest animal in the world?', ARRAY['Elephant','Giraffe','Horse','Camel'], 1),
('general_knowledge', 'Which continent is the Sahara Desert located in?', ARRAY['Asia','Africa','Australia','South America'], 1),
('general_knowledge', 'What is the boiling point of water in Celsius at sea level?', ARRAY['90','95','100','110'], 2),
('general_knowledge', 'What is the currency used in the United Kingdom?', ARRAY['Euro','Dollar','Pound Sterling','Franc'], 2),
('general_knowledge', 'Which planet has the most moons confirmed as of the early 2020s?', ARRAY['Jupiter','Saturn','Uranus','Neptune'], 1),
('general_knowledge', 'What is the human body''s largest organ?', ARRAY['Liver','Brain','Skin','Heart'], 2),
('general_knowledge', 'Which famous scientist developed the theory of relativity?', ARRAY['Isaac Newton','Albert Einstein','Stephen Hawking','Nikola Tesla'], 1),
('general_knowledge', 'What is the capital of Australia?', ARRAY['Sydney','Melbourne','Canberra','Perth'], 2),
('general_knowledge', 'How many legs does a spider have?', ARRAY['6','8','10','12'], 1),
('general_knowledge', 'What is the largest country in the world by land area?', ARRAY['China','United States','Canada','Russia'], 3),
('general_knowledge', 'Which vitamin is produced when human skin is exposed to sunlight?', ARRAY['Vitamin A','Vitamin B12','Vitamin C','Vitamin D'], 3),
('general_knowledge', 'What is the fastest land animal in the world?', ARRAY['Lion','Cheetah','Horse','Antelope'], 1),
('general_knowledge', 'Which ocean is located between Africa and Australia primarily?', ARRAY['Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean'], 2),
('general_knowledge', 'What is the main ingredient in traditional guacamole?', ARRAY['Tomato','Avocado','Onion','Lime'], 1),
('general_knowledge', 'How many chambers does the human heart have?', ARRAY['2','3','4','5'], 2),
('general_knowledge', 'What is the capital of Germany?', ARRAY['Munich','Frankfurt','Hamburg','Berlin'], 3),
('general_knowledge', 'Which metal is liquid at room temperature?', ARRAY['Iron','Mercury','Lead','Zinc'], 1),
('general_knowledge', 'What is the term for an animal that eats both plants and meat?', ARRAY['Herbivore','Carnivore','Omnivore','Scavenger'], 2),
('general_knowledge', 'Which country is famous for inventing pizza?', ARRAY['France','Italy','Greece','Spain'], 1),
('general_knowledge', 'What is the largest internal organ in the human body?', ARRAY['Lungs','Liver','Kidneys','Stomach'], 1),
('general_knowledge', 'How many players are on a standard volleyball team on the court?', ARRAY['5','6','7','8'], 1),
('general_knowledge', 'What is the capital of Spain?', ARRAY['Barcelona','Madrid','Seville','Valencia'], 1),
('general_knowledge', 'Which gas do humans exhale that plants use for photosynthesis?', ARRAY['Oxygen','Carbon dioxide','Nitrogen','Helium'], 1),
('general_knowledge', 'What is the name of the galaxy that contains our solar system?', ARRAY['Andromeda','Milky Way','Whirlpool Galaxy','Triangulum'], 1),
('general_knowledge', 'Which country is home to the Great Barrier Reef?', ARRAY['Indonesia','Philippines','Australia','Thailand'], 2),
('general_knowledge', 'What is the study of weather and atmospheric conditions called?', ARRAY['Geology','Meteorology','Astronomy','Oceanography'], 1),
('general_knowledge', 'How many colors of pigment do humans typically perceive as primary colors (in traditional art)?', ARRAY['2','3','4','5'], 1),
('general_knowledge', 'What is the capital of Russia?', ARRAY['St. Petersburg','Moscow','Novosibirsk','Kazan'], 1),
('general_knowledge', 'Which insect is known for producing honey?', ARRAY['Wasp','Ant','Bee','Beetle'], 2),
('general_knowledge', 'What is the largest bone in the human body?', ARRAY['Tibia','Femur','Humerus','Fibula'], 1),
('general_knowledge', 'Which country consists of over 17,000 islands and is located in Southeast Asia?', ARRAY['Philippines','Indonesia','Malaysia','Thailand'], 1),
('general_knowledge', 'What natural phenomenon is measured using the Richter scale?', ARRAY['Hurricanes','Earthquakes','Tornadoes','Floods'], 1),
('afrobeats', 'Which Nigerian musician is widely credited as the pioneer of the original Afrobeat genre in the 1960s and 1970s?', ARRAY['King Sunny Ade','Fela Kuti','Ebenezer Obey','Rex Lawson'], 1),
('afrobeats', 'What was the name of the Lagos compound where Fela Kuti lived, recorded, and organized resistance to military rule?', ARRAY['Freedom Square','Afrika Shrine','Kalakuta Republic','Independence House'], 2),
('afrobeats', 'The 1976 Fela Kuti album Zombie was a protest against which target?', ARRAY['Record label executives','Rival musicians','The Nigerian military government','Colonial-era police'], 2),
('afrobeats', 'Afrobeat, pioneered by Fela Kuti, is a fusion of jazz, funk, and which West African genre?', ARRAY['Reggae','Highlife','Gospel','Bluegrass'], 1),
('afrobeats', 'In addition to keyboards, which instrument was Fela Kuti famous for playing?', ARRAY['Violin','Trumpet','Drums','Saxophone'], 3),
('afrobeats', 'The performer known as Burna Boy was born with which real name?', ARRAY['Chukwuka Ekweani','Damini Ebunoluwa Ogulu','David Adedeji Adeleke','Divine Ikubor'], 1),
('afrobeats', 'In 2021, Burna Boy became the first Nigerian artist to win a Grammy Award in which category?', ARRAY['Record of the Year','Best New Artist','Best Global Music Album','Best Rap Album'], 2),
('afrobeats', 'Which album won Burna Boy his first Grammy Award?', ARRAY['Love Damini','African Giant','Twice as Tall','Outside'], 2),
('afrobeats', 'Benson Idonije, the first manager of Fela Kuti, is the grandfather of which modern Afrobeats star?', ARRAY['Wizkid','Davido','Rema','Burna Boy'], 3),
('afrobeats', 'The performer known as Wizkid was born with which real name?', ARRAY['David Adedeji Adeleke','Ayodeji Ibrahim Balogun','Damini Ogulu','Chukwuka Ekweani'], 1),
('afrobeats', 'The 2021 hit song Essence, featuring Tems, made Wizkid part of the first Nigerian song to achieve which Billboard milestone?', ARRAY['A number-one debut','A Top 10 spot on the Hot 100','A 52-week chart run','A Grammy nomination for Song of the Year'], 1),
('afrobeats', 'Before his global solo breakthrough, Wizkid gained major international exposure as a featured artist on which Drake single?', ARRAY['Hotline Bling','One Dance','Passionfruit','In My Feelings'], 1),
('afrobeats', 'Wizkid founded his own record label in 2013. What is it called?', ARRAY['Empire Mates Entertainment','Mavin Records','Starboy Entertainment','DMW'], 2),
('afrobeats', 'Which 2020 album, featuring the hit Essence, cemented global recognition for Wizkid as an Afrobeats star?', ARRAY['Sounds from the Other Side','Ayo','Made in Lagos','Superstar'], 2),
('afrobeats', 'The performer known as Davido was born with which real name?', ARRAY['Divine Ikubor','Ahmed Ololade','David Adedeji Adeleke','Damini Ogulu'], 2),
('afrobeats', 'Davido is popularly nicknamed OBO, short for a Yoruba phrase meaning what?', ARRAY['King of the streets','Voice of the people','Child of a wealthy man','Son of the soil'], 2),
('afrobeats', 'What is the name of the record label Davido founded in 2016?', ARRAY['Mavin Records','YBNL Nation','DMW (Davido Music Worldwide)','Starboy Entertainment'], 2),
('afrobeats', 'Which of these songs is a major hit by Davido?', ARRAY['Ye','Ojuelegba','If','Johnny'], 2),
('afrobeats', 'Tiwa Savage was the first female artist signed to which major Nigerian record label?', ARRAY['DMW','YBNL Nation','Mavin Records','Starboy Entertainment'], 2),
('afrobeats', 'Tiwa Savage is widely known by which nickname in Afrobeats circles?', ARRAY['Mama Africa','First Lady of Afrobeat','Queen of Afrobeats','Afro Queen'], 2),
('afrobeats', 'Which Nigerian singer, known for the massively viral 2014 hit Johnny, is nicknamed Mama Africa?', ARRAY['Niniola','Simi','Tiwa Savage','Yemi Alade'], 3),
('afrobeats', 'Which massively viral 2014 song helped launch Yemi Alade to continental fame?', ARRAY['Home','Tangerine','Johnny','Away'], 2),
('afrobeats', 'The performer known as Rema was born with which real name?', ARRAY['Ahmed Ololade','Divine Ikubor','Stanley Omah Didia','Adedamola Adefolahan'], 1),
('afrobeats', 'Rema is signed to which record label, also home to Tiwa Savage and Ayra Starr?', ARRAY['DMW','Starboy Entertainment','Mavin Records','YBNL Nation'], 2),
('afrobeats', 'After a remix featuring Selena Gomez, the Rema song Calm Down set a Billboard record for the most weeks spent on which chart?', ARRAY['Adult Contemporary','Billboard 200','Hot 100','Pop Airplay'], 3),
('afrobeats', 'The performer known as Tems was born with which real name?', ARRAY['Oyinkansola Sarah Aderibigbe','Temilade Openiyi','Simisola Ogunleye','Teniola Apata'], 1),
('afrobeats', 'Tems won her first Grammy Award for a feature on which 2022 hit song?', ARRAY['Rush','Calm Down','Essence','Wait for U'], 3),
('afrobeats', 'Tems was featured on which Beyonce song from the Black Panther: Wakanda Forever soundtrack?', ARRAY['Cuff It','Break My Soul','Lift Me Up','Alien Superstar'], 2),
('afrobeats', 'The performer known as CKay was born with which real name?', ARRAY['David Adedeji Adeleke','Divine Ikubor','Stanley Omah Didia','Chukwuka Ekweani'], 3),
('afrobeats', 'The CKay global viral hit Love Nwantiti first exploded on which platform?', ARRAY['Snapchat','Instagram Reels','TikTok','YouTube Shorts'], 2),
('afrobeats', 'Love Nwantiti originally appeared on which 2019 CKay project, years before it went viral worldwide?', ARRAY['Boyfriend','Watawi','Sad Romance','CKay the First'], 3),
('afrobeats', 'P-Square was a Nigerian musical duo formed by which pair of twin brothers?', ARRAY['Femi and Seun Kuti','Chidi and Chike Ezekwenna','Peter and Paul Okoye','Kunle and Kayode Bello'], 2),
('afrobeats', 'In which Nigerian city were the twin members of P-Square, Peter and Paul Okoye, born?', ARRAY['Abuja','Port Harcourt','Lagos','Jos'], 3),
('afrobeats', 'D''banj, known for the global hit Oliver Twist, was born with which real name?', ARRAY['Chinedu Okoli','Patrick Nnaemeka Okorie','Oladapo Daniel Oyebanjo','Enitan Timi Odetunde'], 2),
('afrobeats', 'D''banj is popularly nicknamed which of these, tied to one of his biggest hits?', ARRAY['Odogwu','Baddo','Kokomaster','Machala'], 2),
('afrobeats', 'D''banj co-founded which influential Nigerian record label with producer Don Jazzy?', ARRAY['Kennis Music','Mavin Records','Trybe Records','Mo''Hits Records'], 3),
('afrobeats', 'After Mo''Hits split, producer Don Jazzy went on to found which record label?', ARRAY['YBNL Nation','Spaceship Records','Mavin Records','Empire Mates Entertainment'], 2),
('afrobeats', 'Veteran Afrobeats star 2Baba, formerly known as 2Face Idibia, was born with which real name?', ARRAY['Timi Odetunde','Innocent Ujah Idibia','Chinedu Okoli','Oladapo Oyebanjo'], 1),
('afrobeats', 'The 2Baba hit African Queen gained major international exposure after being featured in what?', ARRAY['An Olympic opening ceremony','A Hollywood movie soundtrack','A Nike commercial','A Coca-Cola jingle'], 1),
('afrobeats', 'Before going solo, 2Baba was a member of which Nigerian music group?', ARRAY['Danfo Drivers','The Remedies','Trybesmen','Plantashun Boiz'], 3),
('afrobeats', 'Highlife-influenced Afrobeats star Flavour was born with which real name?', ARRAY['Ahmed Ololade','Chinedu Okoli','David Adeleke','Patrick Okorie'], 1),
('afrobeats', 'The highlife genre, a major influence on Nigerian Afrobeats, originated in which West African country?', ARRAY['Senegal','Ivory Coast','Cameroon','Ghana'], 3),
('afrobeats', 'Niger Delta-born singer Timaya built his sound around Afrobeats fused with which style?', ARRAY['Opera','Bluegrass','Dancehall and street rhythms','Country'], 2),
('afrobeats', 'Which artist founded the influential Nigerian record label YBNL Nation?', ARRAY['Wizkid','Burna Boy','Davido','Olamide'], 3),
('afrobeats', 'Rapper Olamide, known for rapping primarily in Yoruba, is popularly nicknamed what?', ARRAY['OBO','Kokomaster','Baddo','Odogwu'], 2),
('afrobeats', 'Which YBNL-signed artist had breakout hits Sungba and Terminator?', ARRAY['Fireboy DML','Omah Lay','Kizz Daniel','Asake'], 3),
('afrobeats', 'The performer known as Asake was born with which real name?', ARRAY['Adedamola Adefolahan','Ahmed Ololade','Stanley Omah Didia','Divine Ikubor'], 1),
('afrobeats', 'The Fireboy DML song Peru had an international remix featuring which global pop star?', ARRAY['Justin Bieber','Chris Brown','Ed Sheeran','Selena Gomez'], 2),
('afrobeats', 'The performer known as Omah Lay was born with which real name?', ARRAY['Oluwatobiloba Anidugbe','Adekunle Kosoko','Stanley Omah Didia','Chukwuka Ekweani'], 2),
('afrobeats', 'Ayra Starr, known for the hit Rush, is signed to which record label?', ARRAY['YBNL Nation','DMW','Starboy Entertainment','Mavin Records'], 3),
('afrobeats', 'The performer known as Ayra Starr was born with which real name?', ARRAY['Teniola Apata','Oyinkansola Sarah Aderibigbe','Simisola Ogunleye','Temilade Openiyi'], 1),
('afrobeats', 'The performer known as Kizz Daniel was born with which real name?', ARRAY['Adekunle Kosoko','Stanley Omah Didia','Oluwatobiloba Daniel Anidugbe','Ahmed Ololade'], 2),
('afrobeats', 'Which massive 2022 Kizz Daniel hit was remixed by artists across Africa?', ARRAY['Sofa','Woju','Buga','Ada'], 2),
('afrobeats', 'Singer Adekunle Gold, known for blending Afrobeats with folk and highlife, was born with which real name?', ARRAY['Innocent Idibia','Adekunle Kosoko','Patrick Okorie','Chinedu Okoli'], 1),
('afrobeats', 'Singer-songwriter Simi, known for the hit Duduke, is married to which fellow Afrobeats artist?', ARRAY['Falz','Praiz','Adekunle Gold','Reekado Banks'], 2),
('afrobeats', 'The performer known as Simi was born with which real name?', ARRAY['Teniola Apata','Temilade Openiyi','Simisola Bolatito Ogunleye','Oyinkansola Aderibigbe'], 2),
('afrobeats', 'Afrobeats singers Teni and Niniola, who share the surname Apata, are related as what?', ARRAY['Mother and daughter','Cousins','Sisters','Aunt and niece'], 2),
('afrobeats', 'Which hit Niniola song, blending Afrobeats with dance and electronic influences, shares its name with a football legend?', ARRAY['Ronaldo','Pele','Messi','Maradona'], 3),
('afrobeats', 'Which artist coined the term Banku music to describe his blend of Nigerian and Ghanaian sounds?', ARRAY['Timaya','Wande Coal','Mr Eazi','Patoranking'], 2),
('afrobeats', 'The performer known as Mr Eazi was born with which real name?', ARRAY['Patrick Okorie','Oluwatosin Ajibade','Wande Ojo','Enitan Odetunde'], 1),
('afrobeats', 'Patoranking, known for infusing dancehall into Afrobeats, scored a major hit alongside Wande Coal titled what?', ARRAY['Available','Girlie O','My Woman, My Everything','Suh Different'], 2),
('afrobeats', 'Wande Coal rose to fame as part of which record label roster, alongside D''banj and Don Jazzy?', ARRAY['DMW','YBNL Nation','Mavin Records','Mo''Hits Records'], 3),
('afrobeats', 'The term Afrobeats, spelled with an s, typically refers to what?', ARRAY['A subgenre of jazz fusion','The modern West African pop sound from the 2000s onward','A single record label catalog','A traditional Ghanaian dance only'], 1),
('afrobeats', 'Amapiano, a South African genre frequently blended with Afrobeats on playlists, originated in which country?', ARRAY['Nigeria','Ivory Coast','Ghana','South Africa'], 3),
('afrobeats', 'Azonto, a dance style popularized alongside Afrobeats music in the early 2010s, originated in which country?', ARRAY['Nigeria','Ghana','South Africa','Democratic Republic of Congo'], 1),
('afrobeats', 'The Nigerian street dance Zanku, popularized around 2018, is closely associated with which artist?', ARRAY['Naira Marley','Zlatan','Burna Boy','Olamide'], 1),
('afrobeats', 'Which country is widely regarded as the epicenter of the modern Afrobeats movement?', ARRAY['Kenya','South Africa','Nigeria','Ghana'], 2),
('afrobeats', 'In Nigerian Pidgin, the word sabi, as in the name SabiGame, means what?', ARRAY['To celebrate','To know or be skilled at','To dance','To sing'], 1),
('afrobeats', 'Burna Boy founded which record label, home to his own music since 2015?', ARRAY['Starboy Entertainment','DMW','Spaceship Records','Mavin Records'], 2),
('afrobeats', 'The Igbo word said to mean a great man is a popular nickname for which artist?', ARRAY['Olamide','D''banj','Burna Boy','Davido'], 2),
('afrobeats', 'Which artist released the 2019 album African Giant, later Grammy-nominated and seen as a defining record of the global Afrobeats rise?', ARRAY['Wizkid','Davido','Rema','Burna Boy'], 3),
('afrobeats', 'Wizkid, Davido, and Burna Boy are often collectively referred to by fans and media as what?', ARRAY['The Golden Trio','The Naija Kings','The Big 3 of Afrobeats','The Lagos Legends'], 2),
('afrobeats', 'Femi Kuti and Seun Kuti, both saxophonists and bandleaders continuing the Afrobeat legacy, are related to Fela Kuti as what?', ARRAY['Nephews','Grandsons','Sons','Unrelated band members'], 2),
('afrobeats', 'The horn-driven, jazz-funk-highlife fusion pioneered by Fela Kuti in the 1960s and 1970s is referred to today by which name, to distinguish it from the modern pop genre?', ARRAY['Afro-funk','Afro-jazz','Afrobeats','Afrobeat'], 3),
('afrobeats', 'Modern Afrobeats music is typically built around which rhythmic backbone?', ARRAY['Bagpipe melodies','Orchestral string sections','Heavy metal guitar riffs','Syncopated percussion and log-drum grooves'], 3);
