-- Seed data for the `questions` table: ~150 questions across the two
-- launch categories (football, general_knowledge). Re-runnable: clears
-- existing rows first so local `supabase db reset` stays idempotent.

truncate table public.questions;

insert into public.questions (category, question, options, correct_answer_index) values
-- ===================== FOOTBALL (75) =====================
('football', 'Which country won the first FIFA World Cup in 1930?', ARRAY['Brazil','Uruguay','Argentina','Italy'], 1),
('football', 'How many players are on a football team on the pitch at one time (excluding substitutes)?', ARRAY['9','10','11','12'], 2),
('football', 'Which club has won the most UEFA Champions League titles?', ARRAY['AC Milan','Bayern Munich','Real Madrid','Liverpool'], 2),
('football', 'Who is the all-time top scorer for the Brazilian national team?', ARRAY['Pele','Ronaldo','Neymar','Romario'], 2),
('football', 'Which country hosted the 2014 FIFA World Cup?', ARRAY['Germany','Brazil','South Africa','Russia'], 1),
('football', 'What is the maximum number of substitutions allowed in a standard modern football match?', ARRAY['3','4','5','6'], 2),
('football', 'Which player has won the most Ballon d''Or awards?', ARRAY['Cristiano Ronaldo','Lionel Messi','Michel Platini','Johan Cruyff'], 1),
('football', 'Which English club is nicknamed "The Red Devils"?', ARRAY['Liverpool','Arsenal','Manchester United','Chelsea'], 2),
('football', 'How long is a standard football match (excluding stoppage time)?', ARRAY['80 minutes','90 minutes','100 minutes','120 minutes'], 1),
('football', 'Which country won the 2018 FIFA World Cup?', ARRAY['Croatia','Belgium','France','Germany'], 2),
('football', 'What shape is a red card used to signal in football?', ARRAY['Rectangle','Square','Circle','Triangle'], 0),
('football', 'Which Argentine player is nicknamed "La Pulga" (The Flea)?', ARRAY['Sergio Aguero','Lionel Messi','Diego Maradona','Angel Di Maria'], 1),
('football', 'Which league is Manchester City part of?', ARRAY['La Liga','Serie A','Premier League','Bundesliga'], 2),
('football', 'What is the offside rule primarily designed to prevent?', ARRAY['Time wasting','Goal hanging','Rough tackles','Handballs'], 1),
('football', 'Which country has won the most FIFA World Cups?', ARRAY['Germany','Argentina','Italy','Brazil'], 3),
('football', 'Which stadium is known as "The Theatre of Dreams"?', ARRAY['Anfield','Old Trafford','Emirates Stadium','Camp Nou'], 1),
('football', 'Who won the Ballon d''Or in 2022?', ARRAY['Lionel Messi','Kylian Mbappe','Karim Benzema','Erling Haaland'], 2),
('football', 'Which Italian club is known as "The Old Lady"?', ARRAY['AC Milan','Inter Milan','Juventus','Napoli'], 2),
('football', 'What competition is nicknamed "The Copa del Rey"?', ARRAY['Italian Cup','French Cup','Spanish Cup','English Cup'], 2),
('football', 'How many minutes make up each half of a standard football match?', ARRAY['40','45','50','60'], 1),
('football', 'Which player scored the "Hand of God" goal in the 1986 World Cup?', ARRAY['Pele','Diego Maradona','Zico','Michel Platini'], 1),
('football', 'Which country did Cristiano Ronaldo represent internationally?', ARRAY['Spain','Brazil','Portugal','Italy'], 2),
('football', 'What is awarded to a team when an opponent commits a foul inside their own penalty area?', ARRAY['Free kick','Corner kick','Penalty kick','Throw-in'], 2),
('football', 'Which club won the UEFA Champions League in 2019?', ARRAY['Barcelona','Liverpool','Tottenham','Real Madrid'], 1),
('football', 'Who is widely considered the founder of "Total Football"?', ARRAY['Johan Cruyff','Rinus Michels','Pep Guardiola','Arrigo Sacchi'], 1),
('football', 'Which country won the UEFA Euro 2020 (played in 2021)?', ARRAY['England','Spain','Italy','France'], 2),
('football', 'What is the term for scoring three goals in a single match by one player?', ARRAY['Brace','Hat-trick','Treble','Triplet'], 1),
('football', 'Which position is primarily responsible for stopping the ball from entering the goal?', ARRAY['Striker','Midfielder','Goalkeeper','Defender'], 2),
('football', 'Which South American country is nicknamed "La Albiceleste"?', ARRAY['Brazil','Chile','Argentina','Uruguay'], 2),
('football', 'What color card is shown for a caution/warning in football?', ARRAY['Red','Yellow','Blue','Orange'], 1),
('football', 'Which club does Lionel Messi play for as of the 2023 MLS season?', ARRAY['Paris Saint-Germain','Barcelona','Inter Miami','Al Hilal'], 2),
('football', 'How many World Cups has Germany won?', ARRAY['2','3','4','5'], 2),
('football', 'Which country is home to the football club Bayern Munich?', ARRAY['Austria','Germany','Switzerland','Netherlands'], 1),
('football', 'What is the standard diameter category of a football, size-wise, used in professional matches?', ARRAY['Size 3','Size 4','Size 5','Size 6'], 2),
('football', 'Football''s governing body FIFA is headquartered in which city?', ARRAY['Paris','Geneva','Zurich','London'], 2),
('football', 'Who managed Manchester United for the longest period, from 1986 to 2013?', ARRAY['Jose Mourinho','Alex Ferguson','David Moyes','Louis van Gaal'], 1),
('football', 'Which player is nicknamed "CR7"?', ARRAY['Cristiano Ronaldo','Ronaldinho','Ronaldo Nazario','Cesc Fabregas'], 0),
('football', 'What is a "clean sheet" in football?', ARRAY['Winning by 5 goals','Not conceding a goal in a match','Scoring in every match','A perfect passing record'], 1),
('football', 'Which country won the first-ever UEFA European Championship in 1960?', ARRAY['France','Spain','Soviet Union','West Germany'], 2),
('football', 'What annual match is contested by the winners of the Premier League and the FA Cup at the start of the season?', ARRAY['FA Cup Final','Community Shield','League Cup Final','Super Cup'], 1),
('football', 'Which Brazilian is widely regarded as one of the greatest players of all time, winning 3 World Cups?', ARRAY['Ronaldinho','Pele','Kaka','Rivaldo'], 1),
('football', 'What is VAR in modern football?', ARRAY['Video Assistant Referee','Virtual Athletic Rating','Verified Action Review','Video Analysis Room'], 0),
('football', 'Which club is based at Camp Nou?', ARRAY['Real Madrid','Atletico Madrid','Barcelona','Sevilla'], 2),
('football', 'Which country won the 2010 FIFA World Cup?', ARRAY['Netherlands','Spain','Germany','Uruguay'], 1),
('football', 'What is the term for a goal scored directly from a corner kick?', ARRAY['Own goal','Olympico','Volley','Header'], 1),
('football', 'Who holds the record for most goals scored in a single World Cup tournament (13 goals)?', ARRAY['Pele','Just Fontaine','Ronaldo','Miroslav Klose'], 1),
('football', 'Which English club plays home matches at "The Emirates Stadium"?', ARRAY['Chelsea','Tottenham Hotspur','Arsenal','West Ham'], 2),
('football', 'What does "extra time" refer to in a knockout football match?', ARRAY['Injury stoppage','Additional 30 minutes after a draw','Half-time break','Penalty shootout'], 1),
('football', 'Which country did Diego Maradona play for internationally?', ARRAY['Uruguay','Argentina','Chile','Colombia'], 1),
('football', 'What is the current trophy awarded to the winner of the FIFA World Cup called?', ARRAY['The Golden Cup','FIFA World Cup Trophy','The Champions Trophy','Jules Rimet Trophy'], 1),
('football', 'Which club won the inaugural Premier League title in the 1992-93 season?', ARRAY['Manchester United','Arsenal','Liverpool','Blackburn Rovers'], 0),
('football', 'Erling Haaland plays club football for which team as of 2023?', ARRAY['Borussia Dortmund','Manchester City','Real Madrid','RB Leipzig'], 1),
('football', 'What is a "nutmeg" in football slang?', ARRAY['A type of formation','Passing the ball through an opponent''s legs','A penalty technique','A defensive tactic'], 1),
('football', 'Which country won the Copa America in 2021?', ARRAY['Brazil','Argentina','Uruguay','Chile'], 1),
('football', 'How many teams competed in the group stage of the FIFA World Cup before 2026 expansion?', ARRAY['24','28','32','36'], 2),
('football', 'Which position typically wears the number 1 shirt?', ARRAY['Striker','Goalkeeper','Center-back','Winger'], 1),
('football', 'What is the name of the biennial club competition contested by European league winners, known as the Champions League?', ARRAY['UEFA Cup','UEFA Champions League','Europa League','Conference League'], 1),
('football', 'Which country''s national team is nicknamed "Les Bleus"?', ARRAY['Belgium','Italy','France','Portugal'], 2),
('football', 'Who is the current (as of 2023) all-time leading goalscorer in Premier League history?', ARRAY['Wayne Rooney','Alan Shearer','Harry Kane','Sergio Aguero'], 1),
('football', 'What is the term for when a match ends level and goes to a shootout?', ARRAY['Sudden death','Penalty shootout','Extra time','Golden goal'], 1),
('football', 'Which club has its home ground at "San Siro" alongside AC Milan?', ARRAY['Juventus','Roma','Inter Milan','Napoli'], 2),
('football', 'What is the maximum squad size typically named for a World Cup tournament?', ARRAY['20','23','26','30'], 2),
('football', 'Which country eliminated Brazil 7-1 in the 2014 World Cup semi-final?', ARRAY['Argentina','Netherlands','Germany','France'], 2),
('football', 'Zinedine Zidane represented which country as a player?', ARRAY['Algeria','Morocco','France','Tunisia'], 2),
('football', 'What is the name for a foul that results in an automatic caution for stopping a clear goal-scoring opportunity?', ARRAY['Professional foul','Handball','Time-wasting','Dissent'], 0),
('football', 'Which country hosted the first FIFA Women''s World Cup in 1991?', ARRAY['USA','China','Sweden','Germany'], 1),
('football', 'What is Kylian Mbappe''s nationality?', ARRAY['Belgian','French','Cameroonian','Senegalese'], 1),
('football', 'Which club did Pep Guardiola manage before Manchester City?', ARRAY['Real Madrid','Bayern Munich','Chelsea','Juventus'], 1),
('football', 'How many points does a win typically earn a team in most football league tables?', ARRAY['1','2','3','4'], 2),
('football', 'What is the term for a match with no goals scored by either team?', ARRAY['Draw','Clean sheet','Goalless draw','Stalemate'], 2),
('football', 'Which country did Ronaldinho represent internationally?', ARRAY['Argentina','Brazil','Portugal','Spain'], 1),
('football', 'What is the primary role of a "sweeper" in football?', ARRAY['Score goals','Take corners','Defend behind the back line','Take throw-ins'], 2),
('football', 'Which African country reached the World Cup semi-finals for the first time in 2022?', ARRAY['Nigeria','Ghana','Morocco','Senegal'], 2),
('football', 'What competition do the winners of each European domestic league qualify for?', ARRAY['Europa League','UEFA Champions League','Conference League','Super Cup'], 1),
('football', 'Which club is Harry Kane associated with as of the 2023-24 season?', ARRAY['Tottenham Hotspur','Bayern Munich','Manchester United','Chelsea'], 1),

-- ===================== GENERAL KNOWLEDGE (75) =====================
('general_knowledge', 'What is the capital of France?', ARRAY['Berlin','Madrid','Paris','Rome'], 2),
('general_knowledge', 'How many continents are there on Earth?', ARRAY['5','6','7','8'], 2),
('general_knowledge', 'What is the largest planet in our solar system?', ARRAY['Earth','Jupiter','Saturn','Neptune'], 1),
('general_knowledge', 'Which gas do plants absorb from the atmosphere for photosynthesis?', ARRAY['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'], 2),
('general_knowledge', 'What is the chemical symbol for gold?', ARRAY['Ag','Au','Gd','Go'], 1),
('general_knowledge', 'Who wrote the play "Romeo and Juliet"?', ARRAY['Charles Dickens','William Shakespeare','Jane Austen','Mark Twain'], 1),
('general_knowledge', 'What is the largest ocean on Earth?', ARRAY['Atlantic Ocean','Indian Ocean','Arctic Ocean','Pacific Ocean'], 3),
('general_knowledge', 'How many days are there in a leap year?', ARRAY['364','365','366','367'], 2),
('general_knowledge', 'What is the smallest country in the world by area?', ARRAY['Monaco','San Marino','Vatican City','Liechtenstein'], 2),
('general_knowledge', 'Which planet is known as the "Red Planet"?', ARRAY['Venus','Mars','Jupiter','Mercury'], 1),
('general_knowledge', 'What is the currency of Japan?', ARRAY['Yuan','Won','Yen','Ringgit'], 2),
('general_knowledge', 'How many bones are there in the adult human body?', ARRAY['186','206','226','246'], 1),
('general_knowledge', 'Who painted the Mona Lisa?', ARRAY['Vincent van Gogh','Pablo Picasso','Leonardo da Vinci','Claude Monet'], 2),
('general_knowledge', 'What is the tallest mountain in the world?', ARRAY['K2','Kangchenjunga','Mount Everest','Lhotse'], 2),
('general_knowledge', 'Which element has the chemical symbol "O"?', ARRAY['Osmium','Oxygen','Gold','Silver'], 1),
('general_knowledge', 'What is the longest river in the world?', ARRAY['Amazon River','Nile River','Yangtze River','Mississippi River'], 1),
('general_knowledge', 'How many strings does a standard guitar have?', ARRAY['4','5','6','7'], 2),
('general_knowledge', 'What is the capital city of Japan?', ARRAY['Osaka','Kyoto','Tokyo','Nagoya'], 2),
('general_knowledge', 'Which organ in the human body is primarily responsible for pumping blood?', ARRAY['Lungs','Liver','Heart','Kidneys'], 2),
('general_knowledge', 'What is the freezing point of water in Celsius?', ARRAY['-10','0','10','32'], 1),
('general_knowledge', 'Which country is known as the "Land of the Rising Sun"?', ARRAY['China','South Korea','Japan','Thailand'], 2),
('general_knowledge', 'What is the largest mammal in the world?', ARRAY['African elephant','Blue whale','Giraffe','Sperm whale'], 1),
('general_knowledge', 'How many colors are there in a rainbow?', ARRAY['5','6','7','8'], 2),
('general_knowledge', 'What is the capital of Italy?', ARRAY['Milan','Venice','Naples','Rome'], 3),
('general_knowledge', 'Which planet is closest to the sun?', ARRAY['Venus','Mercury','Earth','Mars'], 1),
('general_knowledge', 'What is the main language spoken in Brazil?', ARRAY['Spanish','Portuguese','French','Italian'], 1),
('general_knowledge', 'How many players are on a standard basketball team on the court at one time?', ARRAY['4','5','6','7'], 1),
('general_knowledge', 'What is the chemical formula for water?', ARRAY['CO2','H2O','O2','NaCl'], 1),
('general_knowledge', 'Who is known as the "Father of Modern Physics"?', ARRAY['Isaac Newton','Albert Einstein','Galileo Galilei','Niels Bohr'], 1),
('general_knowledge', 'What is the largest desert in the world (by area, including polar deserts)?', ARRAY['Sahara Desert','Arabian Desert','Antarctic Desert','Gobi Desert'], 2),
('general_knowledge', 'Which country gifted the Statue of Liberty to the United States?', ARRAY['United Kingdom','Spain','France','Italy'], 2),
('general_knowledge', 'What is the study of living organisms called?', ARRAY['Chemistry','Physics','Biology','Geology'], 2),
('general_knowledge', 'How many minutes are there in a full day?', ARRAY['1200','1440','1600','1800'], 1),
('general_knowledge', 'Which is the smallest planet in our solar system?', ARRAY['Mars','Mercury','Venus','Pluto'], 1),
('general_knowledge', 'What is the national language of Egypt?', ARRAY['Arabic','Hebrew','Turkish','Persian'], 0),
('general_knowledge', 'Who developed the theory of evolution by natural selection?', ARRAY['Gregor Mendel','Charles Darwin','Louis Pasteur','Isaac Newton'], 1),
('general_knowledge', 'What is the hardest natural substance on Earth?', ARRAY['Gold','Iron','Diamond','Quartz'], 2),
('general_knowledge', 'Which country has the largest population in the world (as of the early 2020s)?', ARRAY['United States','India','China','Indonesia'], 2),
('general_knowledge', 'What do you call a group of lions?', ARRAY['Pack','Pride','Herd','Flock'], 1),
('general_knowledge', 'What is the capital of Canada?', ARRAY['Toronto','Vancouver','Ottawa','Montreal'], 2),
('general_knowledge', 'How many sides does a hexagon have?', ARRAY['5','6','7','8'], 1),
('general_knowledge', 'What is the primary gas found in the Earth''s atmosphere?', ARRAY['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'], 2),
('general_knowledge', 'Who wrote the novel "1984"?', ARRAY['Aldous Huxley','George Orwell','Ray Bradbury','H.G. Wells'], 1),
('general_knowledge', 'What is the tallest animal in the world?', ARRAY['Elephant','Giraffe','Horse','Camel'], 1),
('general_knowledge', 'Which continent is the Sahara Desert located in?', ARRAY['Asia','Africa','Australia','South America'], 1),
('general_knowledge', 'What is the boiling point of water in Celsius at sea level?', ARRAY['90','95','100','110'], 2),
('general_knowledge', 'What is the currency used in the United Kingdom?', ARRAY['Euro','Dollar','Pound Sterling','Franc'], 2),
('general_knowledge', 'Which planet has the most moons confirmed as of the early 2020s?', ARRAY['Jupiter','Saturn','Uranus','Neptune'], 1),
('general_knowledge', 'What is the human body''s largest organ?', ARRAY['Liver','Brain','Skin','Heart'], 2),
('general_knowledge', 'Which famous scientist developed the theory of relativity?', ARRAY['Isaac Newton','Albert Einstein','Stephen Hawking','Nikola Tesla'], 1),
('general_knowledge', 'What is the capital of Australia?', ARRAY['Sydney','Melbourne','Canberra','Perth'], 2),
('general_knowledge', 'How many legs does a spider have?', ARRAY['6','8','10','12'], 1),
('general_knowledge', 'What is the largest country in the world by land area?', ARRAY['China','United States','Canada','Russia'], 3),
('general_knowledge', 'Which vitamin is produced when human skin is exposed to sunlight?', ARRAY['Vitamin A','Vitamin B12','Vitamin C','Vitamin D'], 3),
('general_knowledge', 'What is the fastest land animal in the world?', ARRAY['Lion','Cheetah','Horse','Antelope'], 1),
('general_knowledge', 'Which ocean is located between Africa and Australia primarily?', ARRAY['Atlantic Ocean','Pacific Ocean','Indian Ocean','Arctic Ocean'], 2),
('general_knowledge', 'What is the main ingredient in traditional guacamole?', ARRAY['Tomato','Avocado','Onion','Lime'], 1),
('general_knowledge', 'How many chambers does the human heart have?', ARRAY['2','3','4','5'], 2),
('general_knowledge', 'What is the capital of Germany?', ARRAY['Munich','Frankfurt','Hamburg','Berlin'], 3),
('general_knowledge', 'Which metal is liquid at room temperature?', ARRAY['Iron','Mercury','Lead','Zinc'], 1),
('general_knowledge', 'What is the term for an animal that eats both plants and meat?', ARRAY['Herbivore','Carnivore','Omnivore','Scavenger'], 2),
('general_knowledge', 'Which country is famous for inventing pizza?', ARRAY['France','Italy','Greece','Spain'], 1),
('general_knowledge', 'What is the largest internal organ in the human body?', ARRAY['Lungs','Liver','Kidneys','Stomach'], 1),
('general_knowledge', 'How many players are on a standard volleyball team on the court?', ARRAY['5','6','7','8'], 1),
('general_knowledge', 'What is the capital of Spain?', ARRAY['Barcelona','Madrid','Seville','Valencia'], 1),
('general_knowledge', 'Which gas do humans exhale that plants use for photosynthesis?', ARRAY['Oxygen','Carbon dioxide','Nitrogen','Helium'], 1),
('general_knowledge', 'What is the name of the galaxy that contains our solar system?', ARRAY['Andromeda','Milky Way','Whirlpool Galaxy','Triangulum'], 1),
('general_knowledge', 'Which country is home to the Great Barrier Reef?', ARRAY['Indonesia','Philippines','Australia','Thailand'], 2),
('general_knowledge', 'What is the study of weather and atmospheric conditions called?', ARRAY['Geology','Meteorology','Astronomy','Oceanography'], 1),
('general_knowledge', 'How many colors of pigment do humans typically perceive as primary colors (in traditional art)?', ARRAY['2','3','4','5'], 1),
('general_knowledge', 'What is the capital of Russia?', ARRAY['St. Petersburg','Moscow','Novosibirsk','Kazan'], 1),
('general_knowledge', 'Which insect is known for producing honey?', ARRAY['Wasp','Ant','Bee','Beetle'], 2),
('general_knowledge', 'What is the largest bone in the human body?', ARRAY['Tibia','Femur','Humerus','Fibula'], 1),
('general_knowledge', 'Which country consists of over 17,000 islands and is located in Southeast Asia?', ARRAY['Philippines','Indonesia','Malaysia','Thailand'], 1),
('general_knowledge', 'What natural phenomenon is measured using the Richter scale?', ARRAY['Hurricanes','Earthquakes','Tornadoes','Floods'], 1);
